<?php
include "header.phtml";

$userData = $user->getUserData();
?>

<h1>Hello <?=$userData['name']?></h1>
Here is the complete user array: <pre><?=print_r($userData)?></pre>

<a href="https://brana.textilniskola.cz:5001">freya</a>
<a href="https://brana.textilniskola.cz:5000">bobik</a>
<a href="https://brana.textilniskola.cz/doku">doku</a>
<a href="https://brana.textilniskola.cz/3d">3d tiskárna</a>
<a href="https://brana.textilniskola.cz:5002">heimdal</a>
<a href="?vpn">vpn</a>
<a href="https://mail.textilniskola.cz">mail</a><br />
<a href="?logout">logout</a>
<?php include "footer.phtml"?>
