<?php

include "header.phtml";

const INDENT_REPEAT = 2;
const SEP = " ";

$imageCounter = 1;

function imageHTML(string $imageText, int $id = null, string $imageLink = null, int $indent = null): string {
  global $imageCounter;

  if (is_null($id))
    $id = $imageCounter;

  if (is_null($imageLink))
    $imageLink = "../gate/assets/vpnWinGuide/obr$id.png";
  
  if (is_null($indent)) {
    // try to autodetermine current indent level
    $callLineNum = debug_backtrace()[0]['line'];
    $indent = strlen(explode("<?", file(__FILE__)[$callLineNum-1])[0])/INDENT_REPEAT;
  }

  $SEP = str_repeat(SEP, INDENT_REPEAT);
  $sI = str_repeat($SEP, $indent);
  
  $imageCounter = $id + 1;

  return <<<EOL
<p>
$sI$SEP<span>$imageText</span>
$sI$SEP<a href="#collapseObr$id" data-toggle="collapse">(obrázek)</a>
$sI</p>
$sI<div id="collapseObr$id" class="collapse">
$sI$SEP<button type="button" class="myShit" data-toggle="modal" data-target="#image-closeup" data-id="$imageLink"> 
$sI$SEP$SEP<img class="img-responsive" src="$imageLink" alt="" />
$sI$SEP</button>
$sI</div>

EOL;
}
?>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="guide.js"></script>

<div class="container px-3 py-3 pt-md-5 pb-md-4 mx-auto">
  <div class="mb-5">
    <h3 class="display-3">Připojení k VPN</h3>
    <h4><small>Není to až tak těžké, jen někdo musí napsat ten návod.</small></h4>
    <!--<img src="../gate/assets/vpnWinGuide/obr1.png">-->
  </div>
  <span>Konfigurace je ke stažení <a href="/gate/vpn"><b>zde</b></a>.</span>
</div>

<div class="container">
  <h4>1: Nainstujte program OpenVPN</h4>
  <ol>
    <li>
      V internetovém prohlížeči otevřete stránku <a href="https://openvpn.net/index.php/open-source/downloads.html">stahování OpenVPN</a>
    </li>
    <li>
      <?=imageHTML("Na této stránce klikněte na odkaz pro stažení instalačního souboru pro Windows (končí .exe)")?>
    </li>
    <li>Otevřete nově stažený program
      <ul>
        <li>
          <?=imageHTML("Chrome")?>
        </li>
        <li>
          <?=imageHTML("Mozilla")?>
        </li>
        <li>
          <?=imageHTML("Edge")?>
        </li>
      </ul>
    </li>
  </ol>
</div>

<div class="container">
  <!-- The Modal -->
  <div class="modal modal-flex" id="image-closeup">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-body">
          <img src="" width='100%' height='100%'/>
        </div>
      </div>
    </div>
  </div>
  
</div>

<?php include "footer.phtml"?>
